export const SET_EXPANDED_POST = 'POST_ACTION:SET_EXPANDED_POST';
export const ADD_COMMENT = 'POST_ACTION:ADD_COMMENT';
export const DELETE_COMMENT = 'POST_ACTION:DELETE_COMMENT';
export const UPDATE_COMMENT = 'POST_ACTION:UPDATE_COMMENT';
export const ADD_LIKE_COMMENT = 'POST_ACTION:ADD_LIKE_COMMENT';

