export const USER_LOADING = 'PROFILE_ACTION:USER_LOADING';
export const SET_USER = 'PROFILE_ACTION:SET_USER';
export const USER_LOGOUT = 'PROFILE_ACTION:USER_LOGOUT';
export const GET_USER_REJECTED = 'PROFILE_ACTION:GET_USER_REJECTED';
export const RESET_PASSWORD = 'PROFILE_ACTION:RESET_PASSWORD';
export const RESET_ERROR = 'PROFILE_ACTION:RESET_ERROR';
export const SET_USERS = 'PROFILE_ACTION:SET_USERS';
export const SET_ROLE = 'PROFILE_ACTION:SET_ROLE';
