export const ADD_POST = 'POST_ACTION:ADD_POST';
export const SET_ALL_POSTS = 'POST_ACTION:SET_ALL_POSTS';
export const LOAD_MORE_POSTS = 'POST_ACTION:LOAD_MORE_POSTS';
export const DELETE_POST = 'POST_ACTION:DELETE_POST';
export const UPDATE_POST = 'POST_ACTION:UPDATE_POST';
export const ADD_LIKE = 'POST_ACTION:ADD_LIKE';
export const ACTION_REJECTED = 'POST_ACTION:ACTION_REJECTED';

